version = "3.11.3"
runner.dialect = scala3
style = defaultWithAlign
danglingParentheses.preset = true
rewrite.scala3.preset = common
// remove if some curly braces should be allowed for long classes etc
rewrite.scala3.optionalBraces.enabled = true
maxColumn = 100
